### ISSUE TITLE
any example of post ?

### ISSUE THREAD

**Issue by marxyes** [parse-community/parse-react#43]
Is there any example for creating or do WE just need to use as described in JS SDK ?

initializeParse(
  'YOUR_SERVER_URL',
  'YOUR_APPLICATION_ID',
  'YOUR_JAVASCRIPT_KEY'
);
What Is "YOUR_JAVASCRIPT_KEY' ?

is this npm based on react query? as it same methodology to fetch data

**Comment by davimacedo** [comment]
For creating new object, you can just use the JS SDK, as described in its guides. Javascript key is optional on Parse Server. So, if you don't have it, just don't send this parameter.

**Comment by marxyes** [comment]
Thanks @davimacedo  , 
I also want to know that as this is An experimental package and in alpha stage, Is it suggested to use it on the live react js project / the production project or Do I simply use JS Sdk for my next react js project?

**Comment by davimacedo** [comment]
It is still marked as alpha because we consider it is not sufficiently mature yet, and are waiting more feedback if this library is in the right direction so we can continue the development. On the other hand, we haven't received many bug reports so far. So, I believe that you should first give it a try in development environment and share your feedback so we can turn it into a stable version as soon as possible :)

**Comment by marxyes** [comment]
Hi @davimacedo  thanks for reply,
I have one more question can I use React query on top of this if yes can you please provide me any example? or I don't need to use React query when we are using this pacakge?
TIA

**Comment by davimacedo** [comment]
I believe you would not need to use React Query when using this library to fetch data from a Parse API.

**Comment by marxyes** [comment]
> I believe you would not need to use React Query when using this library to fetch data from a Parse API.

@davimacedo Yes but to perform put patch operation like in react query mutation things I can pass parse JS SDK function in react query right ? or alternatively who approach should I take to make post put patch like operations using this package .

Pardon for Very beginer level questions. TIA

**Comment by davimacedo** [comment]
Yes, I think you can React Query for the other operations together with the Parse JS SDK. I will work on authentication hooks soon for this lib but haven't started yet.
