### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by UsamaAshraf82** [parse-community/parse-react#46]
Question Is this abandoned 
I am asking because i need to use Parse in NextJS server 
So if it is abandoned and no new update is in progress or in near future then i can just use parseJS
kindly guide me because the last update is 6 month ago and it is still in alpha version

**Comment by davimacedo** [comment]
@UsamaAshraf82 It is still an experimental library and we are still trying to get more feedback and input from the community to decide if we should put more effort on this library or not. I believe it can save you time on the Next.js queries, but I understand your concerns on using the experimental library. If you are willed to try it out on your project and share your thoughts, that would be very helpful.
