### ISSUE TITLE
Use in Next.js without getServerSideProps?

### ISSUE THREAD

**Issue by rshov** [parse-community/parse-react#51]
Is it possible to use @parse/react-ssr without having to encode the query inside getServerSideProps?
I would like to have a static page that accesses parse from the front-end, but using getServerSideProps forces it to be server-side rendered.
Thanks!

**Comment by davimacedo** [comment]
would you mind to share the code that you are using to initialize the lib?

**Comment by davimacedo** [comment]
I think the problem is actually this line `import Parse from 'parse'`, right? Or does the error come from `import { useParseQuery, initializeParse } from '@parse/react'`?

**Comment by rshov** [comment]
I actually get the same error if I delete the line `import Parse from 'parse'`.

I think the error is coming from the `@parse/react' package, as that is the first line in that file: parse-react/packages/parse-react/src/index.ts

Maybe that conflicts with what webpack is expecting in Next.js? I don't know enough about webpack, but seems like that might be the problem.

This is the Next error shown in the browser:
![image](https://user-images.githubusercontent.com/10855603/136871174-b76820d2-5b02-4ecc-a640-41850370cbef.png)

And the console has this output:
```
error - C:\my-app-dir\node_modules\@parse\react\dist\index.js:1
import Parse from 'parse';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@parse/react (C:\my-app-dir\.next\server\pages\dashboard.js:18193:18)
    at __webpack_require__ (C:\my-app-dir\.next\server\webpack-runtime.js:25:43)
    at Module../pages/dashboard.tsx (C:\my-app-dir\.next\server\pages\dashboard.js:2389:70) {
  page: '/dashboard'
}
```

**Comment by davimacedo** [comment]
The problem is happening because @parse/react is build with target esnext (which does not work in node.js). I will keep this issue open for us to think about a more convenient way to use the link on next.js without loading data on server. In the meantime, I'd try to do something like this:

```js
import Parse from 'parse'
import { useParseQuery, initializeParse } from '@parse/react-ssr'

// Check if running in browser
if (typeof window !== 'undefined') {
  initializeParse(
    process.env.NEXT_PUBLIC_PARSE_SERVER_URL,
    process.env.NEXT_PUBLIC_PARSE_APP_ID,
    process.env.NEXT_PUBLIC_PARSE_JS_KEY
  )
}

const DashboardPage = () => {

  const parseQuery = new Parse.Query('Project')

  const {
    isLoading,
    results,
    error,
    reload
  } = typeof window !== 'undefined' ? useParseQuery(parseQuery) : {
    isLoading: true,
    results: undefined,
    error: undefined,
    reload: undefined

}

  ...
}
```

**Comment by rshov** [comment]
Perfect, that works! Thanks @davimacedo 
I appreciate your fast responses and fix on this.
